name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  composer-validate:
    name: Composer validate & audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Composer audit
        run: composer audit --locked

  tests:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    needs: composer-validate

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SicseDev/quality-assurance
          fail_ci_if_error: true

  grumphp:
    name: GrumPHP full run
    runs-on: ubuntu-latest
    needs: [composer-validate, tests]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run GrumPHP
        run: vendor/bin/grumphp run
